/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TypographyImport } from './routes/typography'
import { Route as ThankYouImport } from './routes/thank-you'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as NotificationsIndexImport } from './routes/notifications/index'
import { Route as GuidesIndexImport } from './routes/guides/index'
import { Route as FormsIndexImport } from './routes/forms/index'
import { Route as NotificationsNotificationIdImport } from './routes/notifications/$notificationId'
import { Route as GuidesGuideIdImport } from './routes/guides/$guideId'
import { Route as FormsFormIdImport } from './routes/forms/$formId'

// Create/Update Routes

const TypographyRoute = TypographyImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRoute,
} as any)

const ThankYouRoute = ThankYouImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotificationsIndexRoute = NotificationsIndexImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRoute,
} as any)

const GuidesIndexRoute = GuidesIndexImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRoute,
} as any)

const FormsIndexRoute = FormsIndexImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRoute,
} as any)

const NotificationsNotificationIdRoute =
  NotificationsNotificationIdImport.update({
    id: '/notifications/$notificationId',
    path: '/notifications/$notificationId',
    getParentRoute: () => rootRoute,
  } as any)

const GuidesGuideIdRoute = GuidesGuideIdImport.update({
  id: '/guides/$guideId',
  path: '/guides/$guideId',
  getParentRoute: () => rootRoute,
} as any)

const FormsFormIdRoute = FormsFormIdImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouImport
      parentRoute: typeof rootRoute
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyImport
      parentRoute: typeof rootRoute
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdImport
      parentRoute: typeof rootRoute
    }
    '/guides/$guideId': {
      id: '/guides/$guideId'
      path: '/guides/$guideId'
      fullPath: '/guides/$guideId'
      preLoaderRoute: typeof GuidesGuideIdImport
      parentRoute: typeof rootRoute
    }
    '/notifications/$notificationId': {
      id: '/notifications/$notificationId'
      path: '/notifications/$notificationId'
      fullPath: '/notifications/$notificationId'
      preLoaderRoute: typeof NotificationsNotificationIdImport
      parentRoute: typeof rootRoute
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsIndexImport
      parentRoute: typeof rootRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesIndexImport
      parentRoute: typeof rootRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/thank-you': typeof ThankYouRoute
  '/typography': typeof TypographyRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/notifications/$notificationId': typeof NotificationsNotificationIdRoute
  '/forms': typeof FormsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/notifications': typeof NotificationsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/thank-you': typeof ThankYouRoute
  '/typography': typeof TypographyRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/notifications/$notificationId': typeof NotificationsNotificationIdRoute
  '/forms': typeof FormsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/notifications': typeof NotificationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/thank-you': typeof ThankYouRoute
  '/typography': typeof TypographyRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/notifications/$notificationId': typeof NotificationsNotificationIdRoute
  '/forms/': typeof FormsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/thank-you'
    | '/typography'
    | '/forms/$formId'
    | '/guides/$guideId'
    | '/notifications/$notificationId'
    | '/forms'
    | '/guides'
    | '/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/thank-you'
    | '/typography'
    | '/forms/$formId'
    | '/guides/$guideId'
    | '/notifications/$notificationId'
    | '/forms'
    | '/guides'
    | '/notifications'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/thank-you'
    | '/typography'
    | '/forms/$formId'
    | '/guides/$guideId'
    | '/notifications/$notificationId'
    | '/forms/'
    | '/guides/'
    | '/notifications/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ThankYouRoute: typeof ThankYouRoute
  TypographyRoute: typeof TypographyRoute
  FormsFormIdRoute: typeof FormsFormIdRoute
  GuidesGuideIdRoute: typeof GuidesGuideIdRoute
  NotificationsNotificationIdRoute: typeof NotificationsNotificationIdRoute
  FormsIndexRoute: typeof FormsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ThankYouRoute: ThankYouRoute,
  TypographyRoute: TypographyRoute,
  FormsFormIdRoute: FormsFormIdRoute,
  GuidesGuideIdRoute: GuidesGuideIdRoute,
  NotificationsNotificationIdRoute: NotificationsNotificationIdRoute,
  FormsIndexRoute: FormsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/thank-you",
        "/typography",
        "/forms/$formId",
        "/guides/$guideId",
        "/notifications/$notificationId",
        "/forms/",
        "/guides/",
        "/notifications/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/thank-you": {
      "filePath": "thank-you.tsx"
    },
    "/typography": {
      "filePath": "typography.tsx"
    },
    "/forms/$formId": {
      "filePath": "forms/$formId.tsx"
    },
    "/guides/$guideId": {
      "filePath": "guides/$guideId.tsx"
    },
    "/notifications/$notificationId": {
      "filePath": "notifications/$notificationId.tsx"
    },
    "/forms/": {
      "filePath": "forms/index.tsx"
    },
    "/guides/": {
      "filePath": "guides/index.tsx"
    },
    "/notifications/": {
      "filePath": "notifications/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
