@hostAddress=https://votemonitor.staging.heroesof.tech

# Login
POST {{hostAddress}}/api/auth
Content-Type: application/json

{
  "username": "platform@admin.com",
  "password": "L8v1gXFtAWoeFUIEU5wc"
}
###
