# List countries
# @name countries
GET {{$dotenv HOST }}/api/countries
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###
@romaniaId = 51aa4900-30a6-91b7-2728-071542a064ff
# Get an country
GET {{$dotenv HOST }}/api/countries/{{romaniaId}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###
