@romaniaId = 51aa4900-30a6-91b7-2728-071542a064ff

# Add election round
# @name newElectionRound
POST {{$dotenv HOST }}/api/election-rounds
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
    "countryId": "{{romaniaId}}",
    "title": "Some election {{$guid}}",
    "englishTitle": "En: some election",
    "startDate": "{{$datetime 'YYYY-MM-DD' 2 d}}"
}
###

# List election rounds
GET {{$dotenv HOST }}/api/election-rounds
    ?PageNumber=1
    &PageSize=100
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###
@electionRoundId={{newElectionRound.response.body.$.id}}

# Get an election round
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Delete an election round
DELETE  {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Archive an election round
POST  {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}:archive
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Unarchive an election round
POST  {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}:unarchive
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Start an election round
POST  {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}:start
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Unstart an election round
POST  {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}:unstart
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

