@electionRoundId=9a6255a2-2897-4b89-8ecf-d172b712f7d2
@monitoringNgoId=fe7709e3-240c-41ea-9ba2-5739c1a51764
# List forms
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/monitoring-ngo/{{monitoringNgoId}}/forms
      ?pageNumber=1
      &pageSize=10
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Fetch forms version
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/forms:version
Authorization: Bearer {{$dotenv JWT_TOKEN}}
###

# Fetch forms
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/forms:fetchAll
Accept-Encoding: gzip
Authorization: Bearer {{$dotenv JWT_TOKEN}}
###




# Create a form
# @name newForm
POST {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/monitoring-ngo/{{monitoringNgoId}}/forms
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "code": "A2",
  "defaultLanguage": "RO",
  "languages": [
    "RO"
  ],
  "name": {
    "RO": "test form"
  },
  "formType": "ClosingAndCounting"
}

###
@formId = {{newForm.response.body.$.id}}
# Update a form
PUT {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/monitoring-ngo/{{monitoringNgoId}}/forms/{{formId}}
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "code": "A2",
  "defaultLanguage": "RO",
  "languages": [
    "RO",
    "EN"
  ],
  "name": {
    "EN": "test form",
    "RO": "formular de test"
  },
  "formType": "ClosingAndCounting",
  "questions": [
    {
      "$questionType": "numberQuestion",
      "id": "{{$guid}}",
      "code": "A1",
      "text": {
        "EN": "How many PEC members have been appointed",
        "RO": "Câți membri PEC au fost numiți"
      },
      "helptext": {
        "EN": "Please enter a number",
        "RO": "Vă rugăm să introduceți numărul dvs"
      },
      "inputPlaceholder": {
        "EN": "number",
        "RO": "numar"
      }
    },
    {
      "$questionType": "textQuestion",
      "id": "{{$guid}}",
      "code": "A2",
      "text": {
        "EN": "How are you today",
        "RO": "Cum te simți azi"
      },
      "helptext": {
        "EN": "Please enter how are you",
        "RO": "Vă rugăm să introduceți cum sunteți"
      },
      "inputPlaceholder": {
        "EN": "mood",
        "RO": "dispozitie"
      }
    },
    {
      "$questionType": "dateQuestion",
      "id": "{{$guid}}",
      "code": "A3",
      "text": {
        "EN": "Time of arrival",
        "RO": "Timpul sosirii"
      },
      "helptext": {
        "EN": "Please enter exact hour when did you arrive",
        "RO": "Vă rugăm să introduceți ora exactă când ați sosit"
      }
    },
    {
      "$questionType": "singleSelectQuestion",
      "id": "{{$guid}}",
      "code": "B1",
      "text": {
        "EN": "The overall conduct of the opening of this PS was:",
        "RO": "Conducerea generală a deschiderii acestui PS a fost:"
      },
      "helptext": {
        "EN": "Please select a single option",
        "RO": "Vă rugăm să selectați o singură opțiune"
      },
      "options": [
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Very good",
            "RO": "Foarte bun"
          },
          "isFreeText": false,
          "isFlagged": false
        },
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Good",
            "RO": "bun"
          },
          "isFreeText": false,
          "isFlagged": false
        },
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Bad",
            "RO": "Rea"
          },
          "isFreeText": false,
          "isFlagged": false
        },
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Very bad",
            "RO": "Foarte rea"
          },
          "isFreeText": false,
          "isFlagged": true
        },
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Other",
            "RO": "Alta"
          },
          "isFreeText": true,
          "isFlagged": true
        }
      ]
    },
    {
      "$questionType": "multiSelectQuestion",
      "id": "{{$guid}}",
      "code": "B2",
      "text": {
        "EN": "What party/bloc proxies were present at the opening of this PS",
        "RO": "Ce împuterniciri de partid/bloc au fost prezenți la deschiderea acestui PS"
      },
      "helptext": {
        "EN": "Please select as many you want",
        "RO": "Vă rugăm să selectați câte doriți"
      },
      "options": [
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Bloc 1",
            "RO": "Bloc 1"
          },
          "isFreeText": false,
          "isFlagged": false
        },
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Bloc 2",
            "RO": "Bloc 2"
          },
          "isFreeText": false,
          "isFlagged": false
        },
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Bloc 3",
            "RO": "Bloc 3"
          },
          "isFreeText": false,
          "isFlagged": false
        },
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Party 1",
            "RO": "Party 1"
          },
          "isFreeText": false,
          "isFlagged": true
        },
        {
          "id": "{{$guid}}",
          "text": {
            "EN": "Other",
            "RO": "Other"
          },
          "isFreeText": true,
          "isFlagged": true
        }
      ]
    },
    {
      "$questionType": "ratingQuestion",
      "id": "{{$guid}}",
      "code": "C1",
      "text": {
        "EN": "Please rate this form",
        "RO": "Vă rugăm să evaluați acest formular"
      },
      "helptext": {
        "EN": "Please give us a rating",
        "RO": "Vă rugăm să ne dați o evaluare"
      },
      "scale": "OneTo10"
    }
  ]
}

###

# Get a form
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/monitoring-ngo/{{monitoringNgoId}}/forms/{{newForm.response.body.$.id}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Delete a form
DELETE {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/monitoring-ngo/{{monitoringNgoId}}/forms/{{newForm.response.body.$.id}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Draft a form
POST {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/monitoring-ngo/{{monitoringNgoId}}/forms/{{newForm.response.body.$.id}}:draft
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Publish a form
POST {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/monitoring-ngo/{{monitoringNgoId}}/forms/{{newForm.response.body.$.id}}:publish
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###
