@electionRoundId=76c94291-6b84-4dfa-a6b0-380865bb0b9c
@pollingStationId=68bbb272-fccf-4e95-b9a6-776390159932

# Add attachment
# @name newAttachment
POST {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}/attachments
Authorization: Bearer {{$dotenv JWT_TOKEN}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Attachment"; filename="test_attachment.jpg"
Content-Type: image/jpg

< files/test_attachment.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

# List attachments
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}/attachments
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Get an attachment
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}/attachments/{{newAttachment.response.body.$.id}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Delete an attachment
DELETE  {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}/attachments/{{newAttachment.response.body.$.id}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

