@electionRoundId=9a6255a2-2897-4b89-8ecf-d172b712f7d2

# Add polling station
# @name newPollingStation
POST {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
   "level1": "Narnia",
   "level2": "Beruna",
   "number": "1002",
   "displayOrder" :1,
   "address" : "some random address {{$guid}}",
   "tags" :{
      "tag1": "{{$guid}}"
   }
}
###

# import polling stations
# @name newPollingStation
POST {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations:import
Authorization: Bearer {{$dotenv JWT_TOKEN}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="File"; filename="test-data.csv"
Content-Type: text/csv

< files/test-data.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

# Fetch polling stations version
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations:version
Authorization: Bearer {{$dotenv JWT_TOKEN}}
###

# Fetch polling stations
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations:fetchAll
Accept-Encoding: gzip
Authorization: Bearer {{$dotenv JWT_TOKEN}}
###

# List polling stations
POST {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations:list
   ?pageNumber=2
   &pageSize=100
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{

}
###
@pollingStationId ={{newPollingStation.response.body.$.id}}
# Get a polling station
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Delete a polling station
DELETE  {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

