@electionRoundId=1c94724e-b94b-4a7b-965d-05d04f20eac8
@pollingStationId=18207370-c06b-4329-80f6-a2078037de1a

# Add note
# @name newAttachment
POST {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}/notes
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "text": "some interesting and informative note"
}
###

# List notes
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}/notes
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Get an note
GET {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}/notes/{{newAttachment.response.body.$.id}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

# Delete an note
DELETE  {{$dotenv HOST }}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}/notes/{{newAttachment.response.body.$.id}}
Authorization: Bearer {{$dotenv JWT_TOKEN}}

###

