global using FastEndpoints;
global using Feature.IssueReports.Attachments.Specifications;
global using FluentAssertions;
global using FluentValidation.TestHelper;
global using NSubstitute;
global using Vote.Monitor.Core.Services.FileStorage.Contracts;
global using Vote.Monitor.Domain.Entities.IssueReportAttachmentAggregate;
global using Vote.Monitor.Domain.Repository;
global using Vote.Monitor.TestUtils.Fakes.Aggregates;
global using Xunit;
global using IssueReportAttachment = Vote.Monitor.Domain.Entities.IssueReportAttachmentAggregate.IssueReportAttachment;
