export enum Language {
  'AA' = 'AA',
  'AB' = 'AB',
  'AE' = 'AE',
  'AF' = 'AF',
  'AK' = 'AK',
  'AM' = 'AM',
  'AN' = 'AN',
  'AR' = 'AR',
  'AS' = 'AS',
  'AV' = 'AV',
  'AY' = 'AY',
  'AZ' = 'AZ',
  'BA' = 'BA',
  'BE' = 'BE',
  'BG' = 'BG',
  'BI' = 'BI',
  'BM' = 'BM',
  'BN' = 'BN',
  'BO' = 'BO',
  'BR' = 'BR',
  'BS' = 'BS',
  'CA' = 'CA',
  'CE' = 'CE',
  'CH' = 'CH',
  'CO' = 'CO',
  'CR' = 'CR',
  'CS' = 'CS',
  'CU' = 'CU',
  'CV' = 'CV',
  'CY' = 'CY',
  'DA' = 'DA',
  'DE' = 'DE',
  'DV' = 'DV',
  'DZ' = 'DZ',
  'EE' = 'EE',
  'EL' = 'EL',
  'EN' = 'EN',
  'EO' = 'EO',
  'ES' = 'ES',
  'ET' = 'ET',
  'EU' = 'EU',
  'FA' = 'FA',
  'FF' = 'FF',
  'FI' = 'FI',
  'FJ' = 'FJ',
  'FO' = 'FO',
  'FR' = 'FR',
  'FY' = 'FY',
  'GA' = 'GA',
  'GD' = 'GD',
  'GL' = 'GL',
  'GN' = 'GN',
  'GU' = 'GU',
  'GV' = 'GV',
  'HA' = 'HA',
  'HE' = 'HE',
  'HI' = 'HI',
  'HO' = 'HO',
  'HR' = 'HR',
  'HT' = 'HT',
  'HU' = 'HU',
  'HY' = 'HY',
  'HZ' = 'HZ',
  'IA' = 'IA',
  'ID' = 'ID',
  'IE' = 'IE',
  'IG' = 'IG',
  'II' = 'II',
  'IK' = 'IK',
  'IO' = 'IO',
  'IS' = 'IS',
  'IT' = 'IT',
  'IU' = 'IU',
  'JA' = 'JA',
  'JV' = 'JV',
  'KA' = 'KA',
  'KG' = 'KG',
  'KI' = 'KI',
  'KJ' = 'KJ',
  'KK' = 'KK',
  'KL' = 'KL',
  'KM' = 'KM',
  'KN' = 'KN',
  'KO' = 'KO',
  'KR' = 'KR',
  'KS' = 'KS',
  'KU' = 'KU',
  'KV' = 'KV',
  'KW' = 'KW',
  'KY' = 'KY',
  'LA' = 'LA',
  'LB' = 'LB',
  'LG' = 'LG',
  'LI' = 'LI',
  'LN' = 'LN',
  'LO' = 'LO',
  'LT' = 'LT',
  'LU' = 'LU',
  'LV' = 'LV',
  'MG' = 'MG',
  'MH' = 'MH',
  'MI' = 'MI',
  'MK' = 'MK',
  'ML' = 'ML',
  'MN' = 'MN',
  'MR' = 'MR',
  'MS' = 'MS',
  'MT' = 'MT',
  'MY' = 'MY',
  'NA' = 'NA',
  'NB' = 'NB',
  'ND' = 'ND',
  'NE' = 'NE',
  'NG' = 'NG',
  'NL' = 'NL',
  'NN' = 'NN',
  'NO' = 'NO',
  'NR' = 'NR',
  'NV' = 'NV',
  'NY' = 'NY',
  'OC' = 'OC',
  'OJ' = 'OJ',
  'OM' = 'OM',
  'OR' = 'OR',
  'OS' = 'OS',
  'PA' = 'PA',
  'PI' = 'PI',
  'PL' = 'PL',
  'PS' = 'PS',
  'PT' = 'PT',
  'QU' = 'QU',
  'RM' = 'RM',
  'RN' = 'RN',
  'RO' = 'RO',
  'RU' = 'RU',
  'RW' = 'RW',
  'SA' = 'SA',
  'SC' = 'SC',
  'SD' = 'SD',
  'SE' = 'SE',
  'SG' = 'SG',
  'SI' = 'SI',
  'SK' = 'SK',
  'SL' = 'SL',
  'SM' = 'SM',
  'SN' = 'SN',
  'SO' = 'SO',
  'SQ' = 'SQ',
  'SR' = 'SR',
  'SS' = 'SS',
  'ST' = 'ST',
  'SU' = 'SU',
  'SV' = 'SV',
  'SW' = 'SW',
  'TA' = 'TA',
  'TE' = 'TE',
  'TG' = 'TG',
  'TH' = 'TH',
  'TI' = 'TI',
  'TK' = 'TK',
  'TL' = 'TL',
  'TN' = 'TN',
  'TO' = 'TO',
  'TR' = 'TR',
  'TS' = 'TS',
  'TT' = 'TT',
  'TW' = 'TW',
  'TY' = 'TY',
  'UG' = 'UG',
  'UK' = 'UK',
  'UR' = 'UR',
  'UZ' = 'UZ',
  'VE' = 'VE',
  'VI' = 'VI',
  'VO' = 'VO',
  'WA' = 'WA',
  'WO' = 'WO',
  'XH' = 'XH',
  'YI' = 'YI',
  'YO' = 'YO',
  'ZA' = 'ZA',
  'ZH' = 'ZH',
  'ZU' = 'ZU',
}

export const LanguageList: Language[] = [
  Language.AA,
  Language.AB,
  Language.AE,
  Language.AF,
  Language.AK,
  Language.AM,
  Language.AN,
  Language.AR,
  Language.AS,
  Language.AV,
  Language.AY,
  Language.AZ,
  Language.BA,
  Language.BE,
  Language.BG,
  Language.BI,
  Language.BM,
  Language.BN,
  Language.BO,
  Language.BR,
  Language.BS,
  Language.CA,
  Language.CE,
  Language.CH,
  Language.CO,
  Language.CR,
  Language.CS,
  Language.CU,
  Language.CV,
  Language.CY,
  Language.DA,
  Language.DE,
  Language.DV,
  Language.DZ,
  Language.EE,
  Language.EL,
  Language.EN,
  Language.EO,
  Language.ES,
  Language.ET,
  Language.EU,
  Language.FA,
  Language.FF,
  Language.FI,
  Language.FJ,
  Language.FO,
  Language.FR,
  Language.FY,
  Language.GA,
  Language.GD,
  Language.GL,
  Language.GN,
  Language.GU,
  Language.GV,
  Language.HA,
  Language.HE,
  Language.HI,
  Language.HO,
  Language.HR,
  Language.HT,
  Language.HU,
  Language.HY,
  Language.HZ,
  Language.IA,
  Language.ID,
  Language.IE,
  Language.IG,
  Language.II,
  Language.IK,
  Language.IO,
  Language.IS,
  Language.IT,
  Language.IU,
  Language.JA,
  Language.JV,
  Language.KA,
  Language.KG,
  Language.KI,
  Language.KJ,
  Language.KK,
  Language.KL,
  Language.KM,
  Language.KN,
  Language.KO,
  Language.KR,
  Language.KS,
  Language.KU,
  Language.KV,
  Language.KW,
  Language.KY,
  Language.LA,
  Language.LB,
  Language.LG,
  Language.LI,
  Language.LN,
  Language.LO,
  Language.LT,
  Language.LU,
  Language.LV,
  Language.MG,
  Language.MH,
  Language.MI,
  Language.MK,
  Language.ML,
  Language.MN,
  Language.MR,
  Language.MS,
  Language.MT,
  Language.MY,
  Language.NA,
  Language.NB,
  Language.ND,
  Language.NE,
  Language.NG,
  Language.NL,
  Language.NN,
  Language.NO,
  Language.NR,
  Language.NV,
  Language.NY,
  Language.OC,
  Language.OJ,
  Language.OM,
  Language.OR,
  Language.OS,
  Language.PA,
  Language.PI,
  Language.PL,
  Language.PS,
  Language.PT,
  Language.QU,
  Language.RM,
  Language.RN,
  Language.RO,
  Language.RU,
  Language.RW,
  Language.SA,
  Language.SC,
  Language.SD,
  Language.SE,
  Language.SG,
  Language.SI,
  Language.SK,
  Language.SL,
  Language.SM,
  Language.SN,
  Language.SO,
  Language.SQ,
  Language.SR,
  Language.SS,
  Language.ST,
  Language.SU,
  Language.SV,
  Language.SW,
  Language.TA,
  Language.TE,
  Language.TG,
  Language.TH,
  Language.TI,
  Language.TK,
  Language.TL,
  Language.TN,
  Language.TO,
  Language.TR,
  Language.TS,
  Language.TT,
  Language.TW,
  Language.TY,
  Language.UG,
  Language.UK,
  Language.UR,
  Language.UZ,
  Language.VE,
  Language.VI,
  Language.VO,
  Language.WA,
  Language.WO,
  Language.XH,
  Language.YI,
  Language.YO,
  Language.ZA,
  Language.ZH,
  Language.ZU,
]
