/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TypographyImport } from './routes/typography'
import { Route as appRouteImport } from './routes/(app)/route'
import { Route as appIndexImport } from './routes/(app)/index'
import { Route as authSuccessImport } from './routes/(auth)/success'
import { Route as authSetPasswordImport } from './routes/(auth)/set-password'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as authAcceptInviteImport } from './routes/(auth)/accept-invite'
import { Route as appElectionsIndexImport } from './routes/(app)/elections/index'
import { Route as appElectionsElectionRoundIdRouteImport } from './routes/(app)/elections/$electionRoundId/route'
import { Route as appElectionsElectionRoundIdIndexImport } from './routes/(app)/elections/$electionRoundId/index'
import { Route as appElectionsElectionRoundIdSubmissionsImport } from './routes/(app)/elections/$electionRoundId/submissions'
import { Route as appElectionsElectionRoundIdQuickReportsImport } from './routes/(app)/elections/$electionRoundId/quick-reports'
import { Route as appElectionsElectionRoundIdObserversImport } from './routes/(app)/elections/$electionRoundId/observers'
import { Route as appElectionsElectionRoundIdFormsImport } from './routes/(app)/elections/$electionRoundId/forms'
import { Route as appElectionsElectionRoundIdDashboardImport } from './routes/(app)/elections/$electionRoundId/dashboard'

// Create/Update Routes

const TypographyRoute = TypographyImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRoute,
} as any)

const appRouteRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const appIndexRoute = appIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)

const authSuccessRoute = authSuccessImport.update({
  id: '/(auth)/success',
  path: '/success',
  getParentRoute: () => rootRoute,
} as any)

const authSetPasswordRoute = authSetPasswordImport.update({
  id: '/(auth)/set-password',
  path: '/set-password',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const authAcceptInviteRoute = authAcceptInviteImport.update({
  id: '/(auth)/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRoute,
} as any)

const appElectionsIndexRoute = appElectionsIndexImport.update({
  id: '/elections/',
  path: '/elections/',
  getParentRoute: () => appRouteRoute,
} as any)

const appElectionsElectionRoundIdRouteRoute =
  appElectionsElectionRoundIdRouteImport.update({
    id: '/elections/$electionRoundId',
    path: '/elections/$electionRoundId',
    getParentRoute: () => appRouteRoute,
  } as any)

const appElectionsElectionRoundIdIndexRoute =
  appElectionsElectionRoundIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appElectionsElectionRoundIdRouteRoute,
  } as any)

const appElectionsElectionRoundIdSubmissionsRoute =
  appElectionsElectionRoundIdSubmissionsImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => appElectionsElectionRoundIdRouteRoute,
  } as any)

const appElectionsElectionRoundIdQuickReportsRoute =
  appElectionsElectionRoundIdQuickReportsImport.update({
    id: '/quick-reports',
    path: '/quick-reports',
    getParentRoute: () => appElectionsElectionRoundIdRouteRoute,
  } as any)

const appElectionsElectionRoundIdObserversRoute =
  appElectionsElectionRoundIdObserversImport.update({
    id: '/observers',
    path: '/observers',
    getParentRoute: () => appElectionsElectionRoundIdRouteRoute,
  } as any)

const appElectionsElectionRoundIdFormsRoute =
  appElectionsElectionRoundIdFormsImport.update({
    id: '/forms',
    path: '/forms',
    getParentRoute: () => appElectionsElectionRoundIdRouteRoute,
  } as any)

const appElectionsElectionRoundIdDashboardRoute =
  appElectionsElectionRoundIdDashboardImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => appElectionsElectionRoundIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRoute
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/accept-invite': {
      id: '/(auth)/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof authAcceptInviteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/set-password': {
      id: '/(auth)/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof authSetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/success': {
      id: '/(auth)/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof authSuccessImport
      parentRoute: typeof rootRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/elections/$electionRoundId': {
      id: '/(app)/elections/$electionRoundId'
      path: '/elections/$electionRoundId'
      fullPath: '/elections/$electionRoundId'
      preLoaderRoute: typeof appElectionsElectionRoundIdRouteImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/elections/': {
      id: '/(app)/elections/'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof appElectionsIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/elections/$electionRoundId/dashboard': {
      id: '/(app)/elections/$electionRoundId/dashboard'
      path: '/dashboard'
      fullPath: '/elections/$electionRoundId/dashboard'
      preLoaderRoute: typeof appElectionsElectionRoundIdDashboardImport
      parentRoute: typeof appElectionsElectionRoundIdRouteImport
    }
    '/(app)/elections/$electionRoundId/forms': {
      id: '/(app)/elections/$electionRoundId/forms'
      path: '/forms'
      fullPath: '/elections/$electionRoundId/forms'
      preLoaderRoute: typeof appElectionsElectionRoundIdFormsImport
      parentRoute: typeof appElectionsElectionRoundIdRouteImport
    }
    '/(app)/elections/$electionRoundId/observers': {
      id: '/(app)/elections/$electionRoundId/observers'
      path: '/observers'
      fullPath: '/elections/$electionRoundId/observers'
      preLoaderRoute: typeof appElectionsElectionRoundIdObserversImport
      parentRoute: typeof appElectionsElectionRoundIdRouteImport
    }
    '/(app)/elections/$electionRoundId/quick-reports': {
      id: '/(app)/elections/$electionRoundId/quick-reports'
      path: '/quick-reports'
      fullPath: '/elections/$electionRoundId/quick-reports'
      preLoaderRoute: typeof appElectionsElectionRoundIdQuickReportsImport
      parentRoute: typeof appElectionsElectionRoundIdRouteImport
    }
    '/(app)/elections/$electionRoundId/submissions': {
      id: '/(app)/elections/$electionRoundId/submissions'
      path: '/submissions'
      fullPath: '/elections/$electionRoundId/submissions'
      preLoaderRoute: typeof appElectionsElectionRoundIdSubmissionsImport
      parentRoute: typeof appElectionsElectionRoundIdRouteImport
    }
    '/(app)/elections/$electionRoundId/': {
      id: '/(app)/elections/$electionRoundId/'
      path: '/'
      fullPath: '/elections/$electionRoundId/'
      preLoaderRoute: typeof appElectionsElectionRoundIdIndexImport
      parentRoute: typeof appElectionsElectionRoundIdRouteImport
    }
  }
}

// Create and export the route tree

interface appElectionsElectionRoundIdRouteRouteChildren {
  appElectionsElectionRoundIdDashboardRoute: typeof appElectionsElectionRoundIdDashboardRoute
  appElectionsElectionRoundIdFormsRoute: typeof appElectionsElectionRoundIdFormsRoute
  appElectionsElectionRoundIdObserversRoute: typeof appElectionsElectionRoundIdObserversRoute
  appElectionsElectionRoundIdQuickReportsRoute: typeof appElectionsElectionRoundIdQuickReportsRoute
  appElectionsElectionRoundIdSubmissionsRoute: typeof appElectionsElectionRoundIdSubmissionsRoute
  appElectionsElectionRoundIdIndexRoute: typeof appElectionsElectionRoundIdIndexRoute
}

const appElectionsElectionRoundIdRouteRouteChildren: appElectionsElectionRoundIdRouteRouteChildren =
  {
    appElectionsElectionRoundIdDashboardRoute:
      appElectionsElectionRoundIdDashboardRoute,
    appElectionsElectionRoundIdFormsRoute:
      appElectionsElectionRoundIdFormsRoute,
    appElectionsElectionRoundIdObserversRoute:
      appElectionsElectionRoundIdObserversRoute,
    appElectionsElectionRoundIdQuickReportsRoute:
      appElectionsElectionRoundIdQuickReportsRoute,
    appElectionsElectionRoundIdSubmissionsRoute:
      appElectionsElectionRoundIdSubmissionsRoute,
    appElectionsElectionRoundIdIndexRoute:
      appElectionsElectionRoundIdIndexRoute,
  }

const appElectionsElectionRoundIdRouteRouteWithChildren =
  appElectionsElectionRoundIdRouteRoute._addFileChildren(
    appElectionsElectionRoundIdRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appElectionsElectionRoundIdRouteRoute: typeof appElectionsElectionRoundIdRouteRouteWithChildren
  appElectionsIndexRoute: typeof appElectionsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appElectionsElectionRoundIdRouteRoute:
    appElectionsElectionRoundIdRouteRouteWithChildren,
  appElectionsIndexRoute: appElectionsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/typography': typeof TypographyRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/set-password': typeof authSetPasswordRoute
  '/success': typeof authSuccessRoute
  '/elections/$electionRoundId': typeof appElectionsElectionRoundIdRouteRouteWithChildren
  '/elections': typeof appElectionsIndexRoute
  '/elections/$electionRoundId/dashboard': typeof appElectionsElectionRoundIdDashboardRoute
  '/elections/$electionRoundId/forms': typeof appElectionsElectionRoundIdFormsRoute
  '/elections/$electionRoundId/observers': typeof appElectionsElectionRoundIdObserversRoute
  '/elections/$electionRoundId/quick-reports': typeof appElectionsElectionRoundIdQuickReportsRoute
  '/elections/$electionRoundId/submissions': typeof appElectionsElectionRoundIdSubmissionsRoute
  '/elections/$electionRoundId/': typeof appElectionsElectionRoundIdIndexRoute
}

export interface FileRoutesByTo {
  '/typography': typeof TypographyRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/set-password': typeof authSetPasswordRoute
  '/success': typeof authSuccessRoute
  '/': typeof appIndexRoute
  '/elections': typeof appElectionsIndexRoute
  '/elections/$electionRoundId/dashboard': typeof appElectionsElectionRoundIdDashboardRoute
  '/elections/$electionRoundId/forms': typeof appElectionsElectionRoundIdFormsRoute
  '/elections/$electionRoundId/observers': typeof appElectionsElectionRoundIdObserversRoute
  '/elections/$electionRoundId/quick-reports': typeof appElectionsElectionRoundIdQuickReportsRoute
  '/elections/$electionRoundId/submissions': typeof appElectionsElectionRoundIdSubmissionsRoute
  '/elections/$electionRoundId': typeof appElectionsElectionRoundIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/typography': typeof TypographyRoute
  '/(auth)/accept-invite': typeof authAcceptInviteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/set-password': typeof authSetPasswordRoute
  '/(auth)/success': typeof authSuccessRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/elections/$electionRoundId': typeof appElectionsElectionRoundIdRouteRouteWithChildren
  '/(app)/elections/': typeof appElectionsIndexRoute
  '/(app)/elections/$electionRoundId/dashboard': typeof appElectionsElectionRoundIdDashboardRoute
  '/(app)/elections/$electionRoundId/forms': typeof appElectionsElectionRoundIdFormsRoute
  '/(app)/elections/$electionRoundId/observers': typeof appElectionsElectionRoundIdObserversRoute
  '/(app)/elections/$electionRoundId/quick-reports': typeof appElectionsElectionRoundIdQuickReportsRoute
  '/(app)/elections/$electionRoundId/submissions': typeof appElectionsElectionRoundIdSubmissionsRoute
  '/(app)/elections/$electionRoundId/': typeof appElectionsElectionRoundIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/typography'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/set-password'
    | '/success'
    | '/elections/$electionRoundId'
    | '/elections'
    | '/elections/$electionRoundId/dashboard'
    | '/elections/$electionRoundId/forms'
    | '/elections/$electionRoundId/observers'
    | '/elections/$electionRoundId/quick-reports'
    | '/elections/$electionRoundId/submissions'
    | '/elections/$electionRoundId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/typography'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/set-password'
    | '/success'
    | '/'
    | '/elections'
    | '/elections/$electionRoundId/dashboard'
    | '/elections/$electionRoundId/forms'
    | '/elections/$electionRoundId/observers'
    | '/elections/$electionRoundId/quick-reports'
    | '/elections/$electionRoundId/submissions'
    | '/elections/$electionRoundId'
  id:
    | '__root__'
    | '/(app)'
    | '/typography'
    | '/(auth)/accept-invite'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/set-password'
    | '/(auth)/success'
    | '/(app)/'
    | '/(app)/elections/$electionRoundId'
    | '/(app)/elections/'
    | '/(app)/elections/$electionRoundId/dashboard'
    | '/(app)/elections/$electionRoundId/forms'
    | '/(app)/elections/$electionRoundId/observers'
    | '/(app)/elections/$electionRoundId/quick-reports'
    | '/(app)/elections/$electionRoundId/submissions'
    | '/(app)/elections/$electionRoundId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  TypographyRoute: typeof TypographyRoute
  authAcceptInviteRoute: typeof authAcceptInviteRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authSetPasswordRoute: typeof authSetPasswordRoute
  authSuccessRoute: typeof authSuccessRoute
}

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  TypographyRoute: TypographyRoute,
  authAcceptInviteRoute: authAcceptInviteRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authSetPasswordRoute: authSetPasswordRoute,
  authSuccessRoute: authSuccessRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)",
        "/typography",
        "/(auth)/accept-invite",
        "/(auth)/forgot-password",
        "/(auth)/login",
        "/(auth)/set-password",
        "/(auth)/success"
      ]
    },
    "/(app)": {
      "filePath": "(app)/route.tsx",
      "children": [
        "/(app)/",
        "/(app)/elections/$electionRoundId",
        "/(app)/elections/"
      ]
    },
    "/typography": {
      "filePath": "typography.tsx"
    },
    "/(auth)/accept-invite": {
      "filePath": "(auth)/accept-invite.tsx"
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/set-password": {
      "filePath": "(auth)/set-password.tsx"
    },
    "/(auth)/success": {
      "filePath": "(auth)/success.tsx"
    },
    "/(app)/": {
      "filePath": "(app)/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/elections/$electionRoundId": {
      "filePath": "(app)/elections/$electionRoundId/route.tsx",
      "parent": "/(app)",
      "children": [
        "/(app)/elections/$electionRoundId/dashboard",
        "/(app)/elections/$electionRoundId/forms",
        "/(app)/elections/$electionRoundId/observers",
        "/(app)/elections/$electionRoundId/quick-reports",
        "/(app)/elections/$electionRoundId/submissions",
        "/(app)/elections/$electionRoundId/"
      ]
    },
    "/(app)/elections/": {
      "filePath": "(app)/elections/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/elections/$electionRoundId/dashboard": {
      "filePath": "(app)/elections/$electionRoundId/dashboard.tsx",
      "parent": "/(app)/elections/$electionRoundId"
    },
    "/(app)/elections/$electionRoundId/forms": {
      "filePath": "(app)/elections/$electionRoundId/forms.tsx",
      "parent": "/(app)/elections/$electionRoundId"
    },
    "/(app)/elections/$electionRoundId/observers": {
      "filePath": "(app)/elections/$electionRoundId/observers.tsx",
      "parent": "/(app)/elections/$electionRoundId"
    },
    "/(app)/elections/$electionRoundId/quick-reports": {
      "filePath": "(app)/elections/$electionRoundId/quick-reports.tsx",
      "parent": "/(app)/elections/$electionRoundId"
    },
    "/(app)/elections/$electionRoundId/submissions": {
      "filePath": "(app)/elections/$electionRoundId/submissions.tsx",
      "parent": "/(app)/elections/$electionRoundId"
    },
    "/(app)/elections/$electionRoundId/": {
      "filePath": "(app)/elections/$electionRoundId/index.tsx",
      "parent": "/(app)/elections/$electionRoundId"
    }
  }
}
ROUTE_MANIFEST_END */
