@hostAddress=https://localhost:7123
@jwtToken=your_token

# List form templates
GET {{hostAddress}}/api/form-templates
      ?pageNumber=1
      &pageSize=10
Authorization: Bearer {{jwtToken}}

###

# Create a form template
# @name newFormTemplate
POST {{hostAddress}}/api/form-templates
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "code": "A",
  "languages": [
    "RO"
  ],
  "name": {
    "RO": "test form"
  },
  "formType": "ClosingAndCounting"
}

###

# Update a form template
PUT {{hostAddress}}/api/form-templates/{{newFormTemplate.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "code": "A-Form",
  "languages": [
    "RO",
    "EN"
  ],
  "name": {
    "EN": "test form",
    "RO": "formular de test"
  },
  "formType": "ClosingAndCounting",
  "sections": [
    {
      "code": "A",
      "title": {
        "EN": "a section",
        "RO": "o sectiune"
      },
      "questions": [
        {
          "$questionType": "numberInputQuestion",
          "id": "{{$guid}}",
          "code": "A1",
          "text": {
            "EN": "How many PEC members have been appointed",
            "RO": "Câți membri PEC au fost numiți"
          },
          "helptext": {
            "EN": "Please enter a number",
            "RO": "Vă rugăm să introduceți numărul dvs"
          },
          "inputPlaceholder": {
            "EN": "number",
            "RO": "numar"
          }
        },
        {
          "$questionType": "textInputQuestion",
          "id": "{{$guid}}",
          "code": "A2",
          "text": {
            "EN": "How are you today",
            "RO": "Cum te simți azi"
          },
          "helptext": {
            "EN": "Please enter how are you",
            "RO": "Vă rugăm să introduceți cum sunteți"
          },
          "inputPlaceholder": {
            "EN": "mood",
            "RO": "dispozitie"
          }
        },
        {
          "$questionType": "dateInputQuestion",
          "id": "{{$guid}}",
          "code": "A3",
          "text": {
            "EN": "Time of arrival",
            "RO": "Timpul sosirii"
          },
          "helptext": {
            "EN": "Please enter exact hour when did you arrive",
            "RO": "Vă rugăm să introduceți ora exactă când ați sosit"
          }
        }
      ]
    },
    {
      "code": "B",
      "title": {
        "EN": "another section",
        "RO": "inca o sectiune"
      },
      "questions": [
        {
          "$questionType": "singleSelectQuestion",
          "id": "{{$guid}}",
          "code": "B1",
          "text": {
            "EN": "The overall conduct of the opening of this PS was:",
            "RO": "Conducerea generală a deschiderii acestui PS a fost:"
          },
          "helptext": {
            "EN": "Please select a single option",
            "RO": "Vă rugăm să selectați o singură opțiune"
          },
          "options": [
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Very good",
                "RO": "Foarte bun"
              },
              "isFreeText": false,
              "isFlagged": false
            },
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Good",
                "RO": "bun"
              },
              "isFreeText": false,
              "isFlagged": false
            },
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Bad",
                "RO": "Rea"
              },
              "isFreeText": false,
              "isFlagged": false
            },
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Very bad",
                "RO": "Foarte rea"
              },
              "isFreeText": false,
              "isFlagged": true
            },
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Other",
                "RO": "Alta"
              },
              "isFreeText": true,
              "isFlagged": true
            }
          ]
        },
        {
          "$questionType": "multiSelectQuestion",
          "id": "{{$guid}}",
          "code": "B2",
          "text": {
            "EN": "What party/bloc proxies were present at the opening of this PS",
            "RO": "Ce împuterniciri de partid/bloc au fost prezenți la deschiderea acestui PS"
          },
          "helptext": {
            "EN": "Please select as many you want",
            "RO": "Vă rugăm să selectați câte doriți"
          },
          "options": [
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Bloc 1",
                "RO": "Bloc 1"
              },
              "isFreeText": false,
              "isFlagged": false
            },
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Bloc 2",
                "RO": "Bloc 2"
              },
              "isFreeText": false,
              "isFlagged": false
            },
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Bloc 3",
                "RO": "Bloc 3"
              },
              "isFreeText": false,
              "isFlagged": false
            },
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Party 1",
                "RO": "Party 1"
              },
              "isFreeText": false,
              "isFlagged": true
            },
            {
              "id": "{{$guid}}",
              "text": {
                "EN": "Other",
                "RO": "Other"
              },
              "isFreeText": true,
              "isFlagged": true
            }
          ]
        }
      ]
    },
    {
      "code": "C",
      "title": {
        "EN": "The last section",
        "RO": "Ultima sectiune"
      },
      "questions": [
        {
          "$questionType": "ratingQuestion",
          "id": "{{$guid}}",
          "code": "C1",
          "text": {
            "EN": "Please rate this form",
            "RO": "Vă rugăm să evaluați acest formular"
          },
          "helptext": {
            "EN": "Please give us a rating",
            "RO": "Vă rugăm să ne dați o evaluare"
          },
          "scale": "OneTo10"
        }
      ]
    }
  ]
}

###

# Get a form template
GET {{hostAddress}}/api/form-templates/{{newFormTemplate.response.body.$.id}}
Authorization: Bearer {{jwtToken}}

###

# Delete a form template
DELETE {{hostAddress}}/api/form-templates/{{newFormTemplate.response.body.$.id}}
Authorization: Bearer {{jwtToken}}

###

# Draft a form template
POST {{hostAddress}}/api/form-templates/{{newFormTemplate.response.body.$.id}}:draft
Authorization: Bearer {{jwtToken}}

###

# Publish a form template
POST {{hostAddress}}/api/form-templates/{{newFormTemplate.response.body.$.id}}:publish
Authorization: Bearer {{jwtToken}}

###