@hostAddress=https://localhost:7123
@jwtToken=your_token
@electionRoundId=1c94724e-b94b-4a7b-965d-05d04f20eac8

# Add polling station
# @name newPollingStation
POST {{hostAddress}}/api/election-rounds/{{electionRoundId}}/polling-stations
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
     "displayOrder" :1,
     "address" : "some random address {{$guid}}",
     "tags" :{
        "tag1": "{{$guid}}"
     }
}
###

# List polling stations
GET {{hostAddress}}/api/election-rounds/{{electionRoundId}}/polling-stations
Authorization: Bearer {{jwtToken}}

###
@pollingStationId ={{newPollingStation.response.body.$.id}}
# Get a polling station
GET {{hostAddress}}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}
Authorization: Bearer {{jwtToken}}

###

# Delete a polling station
DELETE  {{hostAddress}}/api/election-rounds/{{electionRoundId}}/polling-stations/{{pollingStationId}}
Authorization: Bearer {{jwtToken}}

###

